### ISSUE TITLE
how to create the chunk lists

### ISSUE THREAD

**Issue by duceduc** [marco-lancini/utils#141]
Hi. Can you explained in more details on how I can create these chunk lists? What I need to download? I am at lost. Thank you.
https://github.com/marco-lancini/utils/tree/main/terraform/cloudflare-gateway-adblocking#keeping-the-domain-list-up-to-date

**Comment by marco-lancini** [comment]
Hi, did you read the full original blog post?

https://blog.marcolancini.it/2022/blog-serverless-ad-blocking-with-cloudflare-gateway/

The [sample action](https://github.com/marco-lancini/utils/blob/main/terraform/cloudflare-gateway-adblocking/action-update-lists.yml) provided will keep the domain list up to date, then the [Terraform code](https://github.com/marco-lancini/utils/blob/main/terraform/cloudflare-gateway-adblocking/gateway-policy.tf) will automatically split it into Cloudflare lists.

Hope this helps!

**Comment by duceduc** [comment]
Hello. I had a quick minute and read about [Terraform](https://developer.hashicorp.com/terraform) and how it is used with [Cloudflare](https://blog.cloudflare.com/getting-started-with-terraform-and-cloudflare-part-1/). I was able to use all your excerpts provided in your [blog post](https://blog.marcolancini.it/2022/blog-serverless-ad-blocking-with-cloudflare-gateway/) and managed to setup a [github action workflow](https://docs.github.com/en/actions/using-workflows) repo to update the pihole adblock list. The end results I am able to connect to [cloudflare zero trust](https://developers.cloudflare.com/cloudflare-one/) using my mobile AND ads are being blocked. yah!

Since you mentioned that the ablock list is stored locally and you setup github action workflow to run a monthly update, I am assuming you perform a pull request locally to your local machine? How is the [terraform code](https://github.com/marco-lancini/utils/blob/main/terraform/cloudflare-gateway-adblocking/gateway-policy.tf) splitting the list to cloudflare by means of an automation? The other a little issue with the github action is that the PR needs to be manually approve. The github docs states that the auto merge feature is available for enterprise, pro and free accounts (repo must be public) users. However, I am unable to set this auto merge, the feature is not visible. Possibly a bug or it has been removed for free accounts.

**Comment by marco-lancini** [comment]
> Since you mentioned that the ablock list is stored locally and you setup github action workflow to run a monthly update, I am assuming you perform a pull request locally to your local machine? 

The list is stored in the same repo where you run the GitHub action, see: https://github.com/marco-lancini/utils/blob/main/terraform/cloudflare-gateway-adblocking/cloudflare/lists/pihole_domain_list.txt

> How is the [terraform code](https://github.com/marco-lancini/utils/blob/main/terraform/cloudflare-gateway-adblocking/gateway-policy.tf) splitting the list to cloudflare by means of an automation? 

See: https://github.com/marco-lancini/utils/blob/main/terraform/cloudflare-gateway-adblocking/gateway-policy.tf#L46-76

> The other a little issue with the github action is that the PR needs to be manually approve. The github docs states that the auto merge feature is available for enterprise, pro and free accounts (repo must be public) users. However, I am unable to set this auto merge, the feature is not visible. Possibly a bug or it has been removed for free accounts.

Auto merge is not available for free accounts
