### ISSUE TITLE
pip3 install -r requirements.txt pip3 not found

### ISSUE THREAD

**Issue by nachogon** [marco-lancini/utils#36]
Hi, first of all I would like to thank for the outstanding work you do.

I'm in the process of deploying kubespray in my homelab (https://www.marcolancini.it/2019/blog-deploy-kubernetes-lab/) as said here.

Nevertheless when I'm on the ansible-worker container everytime I try to run a command I get this error.

/src # pip3 install -r requirements.txt
/bin/sh: pip3: not found

It is possible that I'm the issue, I would appreciate any help.

Warm regards

**Comment by nachogon** [comment]
I found the issue:
I was following this article: https://www.marcolancini.it/2019/blog-deploy-kubernetes-lab/ 
It seems step: 

# Install dependencies from requirements.txt
/kubespray $ pip3 install -r requirements.txt
# Copy inventory/sample as inventory/mycluster
/kubespray $ cp -r inventory/sample inventory/mycluster

is already done in the updated image, this can be closed now.

have a great day.

**Comment by marco-lancini** [comment]
Thanks for the kind words!
Glad to hear it worked in the end :)
